name: Update views.json

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * *"  # codziennie o 6:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Fetch traffic data
      - name: Fetch traffic
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/KamilDziuk/blog/traffic/views \
               > views.json

      # Commit and push changes
      - name: Commit and push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add views.json
          git commit -m "Update views" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/KamilDziuk/blog.git
          git push origin main
          
         
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/KamilDziuk/blog.git
          
          git push origin main
